server:
  port: 8081

spring:
  application:
    name: chat-system
  cloud:
    nacos:
      # 必须添加服务器地址，否则会默认连接 localhost
      server-addr: 192.168.202.155:8848
      discovery:
        group: DEFAULT_GROUP
      config:
        file-extension: yaml
        group: DEFAULT_GROUP
  config:
    import:
      - nacos:common-datasource.yaml?group=DEFAULT_GROUP&refresh=true
      - nacos:common-redis.yaml?group=DEFAULT_GROUP&refresh=true
      - nacos:chat-system.yaml?group=DEFAULT_GROUP&refresh=true
      - nacos:common-actuator.yaml?group=DEFAULT_GROUP&refresh=true

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml