server:
  port: 8082 #

spring:
  application:
    name: chat-auth
  cloud:
    nacos:
      server-addr: 10.202.108.50:8848
      discovery:
        group: DEFAULT_GROUP
      config:
        file-extension: yaml
        group: DEFAULT_GROUP
  config:
    import:
      - nacos:common-datasource.yaml?group=DEFAULT_GROUP&refresh=true
      - nacos:common-redis.yaml?group=DEFAULT_GROUP&refresh=true
      - nacos:chat-auth.yaml?group=DEFAULT_GROUP&refresh=true
      - nacos:common-actuator.yaml?group=DEFAULT_GROUP&refresh=true

