server:
  port: 8000

spring:
  application:
    name: chat-gateway
  cloud:
    nacos:
      server-addr: 10.202.108.50:8848
      discovery:
        group: DEFAULT_GROUP
      config:
        file-extension: yaml
        group: DEFAULT_GROUP
  config:
    import:
      # refresh=true：告知 Nacos 客户端监听此 Data ID 的变更并推送 RefreshEvent
      - nacos:chat-gateway.yaml?group=DEFAULT_GROUP&refresh=true
